window.BRIG_STRINGS = {
"The content could not load. Please refresh the page.": "De inhoud kan niet laden. Ververs de pagina.",
"Not yet": "Nog niet",
"Aware": "Beginner",
"Explorer": "Ontdekker",
"Integrator": "Professional",
"Creator": "Expert",
"Confident with the basics": "Zelfverzekerd over de basis",
"I want AI to be genuinely useful in daily life.": "Ik wil dat AI echt nuttig is in het dagelijks leven.",
"Genuinely capable": "Echt capabel",
"I want to build things with it and judge them well.": "Ik wil er dingen mee bouwen en ze goed beoordelen.",
"Able to guide others": "In staat om anderen te begeleiden",
"I want to help other people use it well.": "Ik wil anderen helpen het goed te gebruiken.",
"Your data was removed from this device. Removing it from our storage failed, so please contact us and we will finish it.": "Je gegevens zijn van dit apparaat verwijderd. Het verwijderen uit onze opslag is mislukt, neem contact met ons op.",
"Use something real, not a practice example": "Gebruik iets uit de praktijk, geen oefenvoorbeeld",
"It comes from your own life or work.": "Het is onderdeel van je eigen leven of werk.",
"Show the parts this level asks for": "Laat de onderdelen zien die dit level nodig heeft",
"The things the level describes are visible in what you made.": "De dingen die het level beschrijft zijn zichtbaar in wat je hebt gemaakt.",
"Include the check or step that is required": "Voeg de controle of stap toe die vereist is",
"You did the checking step, not only the output.": "Je hebt de controlestap gedaan, niet alleen de output.",
"Write down one reflection": "Schrijf één reflectie op",
"Kept as evidence. It is never graded.": "Bewaard als bewijs. Het wordt nooit beoordeeld.",
"Use a harder or more important case": "Gebruik een moeilijkere of belangrijkere voorbeeld",
"More complex than your last assignment, and it mattered.": "Complexer dan je vorige opdracht, en het deed ertoe.",
"Make your judgement visible": "Maak je oordeel zichtbaar",
"Show a comparison, a reasoned choice, or a cross check.": "Laat een vergelijking zien, een weloverwogen keuze of een extra controle.",
"Let one objective check confirm it": "Laat één objectieve controle het bevestigen",
"A source matched, a number added up, or a test ran.": "Een bron kwam overeen, een aantal werd opgeteld, of er werd een test uitgevoerd.",
"Make something reusable": "Maak iets wat je kunt herbruiken",
"A template with blanks, a check step, or a written rule.": "Een sjabloon met placeholders, een controlestap, of een geschreven regel.",
"Make it usable by someone else": "Maak het bruikbaar voor iemand anders",
"Add guidance or clear criteria.": "Voeg richtlijnen of duidelijke criteria toe.",
"Use it on a real case, or hand it to a person": "Gebruik het bij een echte zaak, of lever het op bij iemand",
"It has been used or given to someone.": "Het is gebruikt of aan iemand opgeleverd.",
"Doing the work": "Doe het werk",
"First real task": "Eerste echte taak",
"Hand in your first assignment.": "Lever je eerste opdracht in.",
"Ten in the wild": "Tien in het wild",
"Hand in ten assignments.": "Lever tien opdrachten in.",
"Fifty in the wild": "Vijftig in het wild",
"Hand in fifty assignments.": "Lever vijftig opdrachten in.",
"Own idea": "Eigen idee",
"Hand in a task you described yourself.": "Lever een taak in die je zelf beschreef.",
"Spacing": "Afstand",
"Came back": "Teruggekomen",
"Return to a skill on or after its due date.": "Keer terug naar een vaardigheid op of na de deadline.",
"Full ramp": "Volledige helling",
"Do four spaced assignments on one skill.": "Doe vier opdrachten die een vaardigheid trainen op gespreide dagen.",
"Three days running": "Drie dagen achter elkaar",
"Keep a three day streak.": "Houd een reeks van drie dagen aan.",
"Two weeks running": "Twee weken achter elkaar",
"Keep a fourteen day streak.": "Houd de reeks van veertien dagen vast.",
"Back on it": "Weer aan het werk",
"Return and hand in after a week or more away.": "Keer terug en lever het in na een week of langere afwezigheid.",
"Levels earned": "Behaalde niveaus",
"Pass a level up test to Explorer.": "Haal een level up-test voor Ontdekker.",
"Pass a level up test to Integrator.": "Haal een level up-test voor Professional.",
"Pass a level up test to Creator.": "Doorslag voor een level-up test voor Expert",
"Held out": "Heeft het gehouden",
"Answer a question you had never seen before.": "Beantwoord een vraag die je nog nooit eerder hebt gezien.",
"Area moved": "Gebied verplaatst",
"Lift a whole area to a new level.": "Ga naar het volgende niveau.",
"Reached your aim": "Je doel is bereikt",
"Meet what you are aiming for in every area.": "Bereik wat je op elk gebied nastreeft.",
"Breadth and honesty": "Diepgang en Oprechtheid",
"Grounded": "Gefundeerd",
"Place every area in the scan.": "Voltooi elk gebied in de scan.",
"Well rounded": "Goed afgerond",
"Hand in work in five different areas.": "Werk in vijf verschillende gebieden.",
"Straight mirror": "Eerlijk en Oprecht",
"Judge yourself accurately on five skills in a row.": "Beoordeel jezelf nauwkeurig op vijf vaardigheden achter elkaar.",
"Careful hands": "Met uiterste zorg",
"Hand in five assignments in Responsible use.": "Lever vijf opdrachten in in Verantwoordelijk gebruik.",
"Badge earned": "Insigne verdiend",
"Sign in": "Inloggen",
"Set up": "Opzet",
"Insight scan": "Insight-scan",
"Where you stand": "Je huidige status",
"Practice": "Praktijk",
"Level up": "Level up",
"Your progress": "Jouw vooruitgang",
"Privacy and legal": "Privacy en juridische zaken",
"Portfolio": "Portefeuille",
"Your account": "Jouw account",
"A name is required.": "Een naam is vereist.",
"Reset link sent to your email.": "Link reset, gestuurd naar je e-mail.",
"Could not send the reset email. Try again.": "Kon de resetmail niet versturen. Probeer het opnieuw.",
"Could not delete. Sign in again and retry.": "Kon niet verwijderen. Log opnieuw in en probeer het opnieuw.",
"Help improve Brigvanti with anonymous usage analytics? We use Google Analytics with advertising off, and nothing runs unless you allow it. Details and the off switch are in": "Help Brigvanti verbeteren met anonieme gebruiksanalyse? We gebruiken Google Analytics met advertenties uitgeschakeld, en niets is actief tenzij je het toestaat. Details en de uitknop vind je in onder het privacy regelement",
"No thanks": "Nee, dank je",
"Allow": "Sta toe",
"Brigvanti": "Brigvanti",
"Go back": "Ga terug",
"you@example.com": "you@example.com",
"At least six characters": "Minstens zes characters",
"Build real AI skill on your own work": "Bouw echte AI-vaardigheden op in de praktijk!",
"Short assignments built on the tasks you already do. Your coach guides you. Nothing here is a test you can fail.": "Korte opdrachten die voortbouwen op de taken die je al doet. Je AI-coach begeleidt je. Niets hier is een test om je te laten falen.",
"Continue with Google": "Ga verder met Google",
"or use your email": "Of gebruik je e-mailadres",
"Email address": "E-mailadres",
"Password": "Wachtwoord",
"By continuing you agree to how we handle your data.": "Door verder te gaan, ga je akkoord met hoe wij met je gegevens omgaan.",
"Read privacy and legal": "Lees onze privacy en legal statement",
"Hide password": "Wachtwoord verbergen",
"Show password": "Toon wachtwoord",
"Create account": "Account aanmaken",
"Already have an account?": "Heb je al een account?",
"New to Brigvanti?": "Nieuw bij Brigvanti?",
"Create one": "Maak een account aan",
"Sign in is not available right now. Please reload the page.": "Inloggen is momenteel niet beschikbaar. Laad de pagina opnieuw.",
"Enter a valid email address to continue.": "Voer een geldig e-mailadres in om verder te gaan.",
"Enter a password of at least six characters.": "Voer een wachtwoord in van minstens zes tekens.",
"Three things that stay true": "Drie dingen die waar blijven",
"Read these once. They hold for the whole pilot.": "Lees deze één keer. Ze blijven de hele pilot geldig",
"Your level is advice, never a verdict": "Het getoonde niveau is een inzicht op basis van je scan en geen oordeel",
"It is a mirror you may disagree with. It is not a qualification. It decides nothing about your job.": "Het is een reflectie waar je het niet mee eens hoeft te zijn. Het is geen kwalificatie. Het bepaalt niets over je baan.",
"The coach guides you, it never scores you": "De AI-coach begeleidt je en geeft je nooit een score",
"Moving up a level is decided by fixed checks and by what you confirm yourself.": "Of je een niveau omhoog gaat, wordt bepaald door vaste controles en door wat je zelf bevestigt.",
"Use real tasks, but never private data": "Gebruik echte taken, maar nooit persoonlijke en/of bedrijfsdata",
"Leave out bank details, ID numbers, health information and other people's personal data.": "Gebruik geen bankgegevens, ID-nummers, gezondheidsinformatie en persoonlijke gegevens van anderen.",
"Your text leaves this app when you use the coach": "Je tekst verlaat deze app zodra je de coach gebruikt.",
"To give feedback, the coach sends what you wrote to our AI provider. That processing is not limited to Europe. Never enter private or sensitive data.": "Om feedback te geven, stuurt de AI-coach wat je hebt geschreven naar onze AI-provider. Die verwerking is niet beperkt tot Europa. Voer nooit privé- of gevoelige gegevens in.",
"Read the full statement": "Lees de volledige verklaring",
"I understand, let us begin": "Ik begrijp het, laten we beginnen",
"Before you start": "Voordat je begint",
"At work": "Op het werk",
"I want to be stronger in my job.": "Ik wil sterker worden in mijn werk.",
"In my own life": "In mijn eigen leven",
"I am not doing this for a job.": "Ik doe dit niet voor een baan.",
"Both": "Beide",
"My work and my daily life.": "Mijn werk en mijn dagelijks leven.",
"Change your focus": "Verander je focus",
"What brings you here?": "Wat brengt je hier?",
"This only sets the level you are aiming for. It never changes how you are placed.": "Dit bepaalt alleen het niveau waar je naar streeft. Het verandert nooit hoe je geplaatst wordt.",
"Update what you are aiming for, then re-run the scan.": "Verander je doen en doe de scan opnieuw.",
"A few quick things, then the scan begins. You can change any of this later.": "Nog een paar vragen en dan begint de scan. Je kunt dit later veranderen.",
"Your first name": "Je voornaam",
"What should your coach call you?": "Hoe wil je dat de AI-coach je noemt?",
"A nickname is fine. This is needed to continue.": "Een bijnaam is prima. Dit is nodig om door te gaan.",
"Which role is the closest match?": "Welke rol past matched het beste bij jou?",
"Pick the nearest one. It does not have to be exact.": "Kies de dichtstbijzijnde. Het hoeft niet exact te zijn.",
"My role is not listed": "Mijn functie staat niet vermeld",
"Choose what you are aiming for instead.": "Kies in plaats daarvan wat je doel is.",
"What are you aiming for?": "Waar wil je je op richten?",
"Pick the honest one, not the flattering one. You can raise it whenever you like.": "Kies de eerlijkste keuze, niet diegene waarbij je het prettigst bij voelt. Je kunt hem verandere wanneer je maar wilt.",
"Show me the role list again": "Laat me de functielijst nog eens zien",
"Which parts of life do you want to practise on?": "Op welke onderdelen van je leven wil je oefenen?",
"Optional. Choose up to three. The scan starts with these areas, and their tasks come first when you practise.": "Optioneel. Kies maximaal drie opties. De scan begint met deze gebieden uit te vragen. De opdrachten worden gebasseerd op jouw keuzes.",
"Start the scan": "Begin met de scan",
"I do not use them": "Ik gebruik AI-tools niet",
"I have tried once or twice": "Ik heb AI één of twee keer geprobeerd",
"I use them sometimes": "Ik gebruik AI soms",
"I use them most days": "Ik gebruik AI bijna elke dag",
"I do not use AI": "Ik gebruik geen AI",
"I take the answer as it comes": "Ik accepteerd het antwoord zoals het wordt aangeboden",
"I skim it and adjust it": "Ik scan het vluchtig en pas het aan",
"I always check it and ask again": "Ik controleer het antwoord altijd en vraag het nogmaals als het antwoord onduidelijk is",
"Two quick questions": "Twee snelle vragen",
"These only decide where the scan starts. Nothing is placed until you show it.": "Deze bepalen alleen waar de scan begint. Er gebeurt niets totdat je het demonstreert.",
"Do you use AI tools in your daily life or work?": "Gebruik je AI-tools in je dagelijks leven of werk?",
"When AI gives you an answer, what do you usually do?": "Wat doe je meestal als AI je een antwoord geeft?",
"Getting started": "Beginnen",
"Choose the highest statement that is true for you. Then you show it, because the statement alone does not set your level.": "Kies de uitspraak die het beste bij jou past. En bewijs het, want alleen de keuze bepaalt het niveau niet.",
"Area {0} of {1} · {2} placed so far.": "Gebied {0} van {1} · {2} tot nu toe geplaatst.",
"None of these fit me yet.": "Geen van deze keuzes past bij mij.",
"Skip this skill": "Sla deze vaardigheid over",
"Skill {0} of {1}": "Vaardigheid {0} van {1}",
"That is correct": "Dat klopt",
"Not this time": "Niet deze keer",
"Continue": "Ga verder",
"Check my answer": "Controleer mijn antwoord",
"{0} is scanned": "{0} is gescand",
"You are at <b>{0}</b> here.": "Je bent hier <b>{0}</b>.",
"Start practising": "Begin met oefenen",
"You can stop here and come back. Everything is saved.": "Je kunt hier stoppen en terugkomen. Alles is opgeslagen.",
"Go to next domain": "Ga naar het volgende domein",
"Go to your progress": "Ga naar je voortgang",
"Area complete": "Gebied voltooid",
"Every area is placed": "Elk gebied is gescanned",
"You have a full picture now.": "Je hebt nu het volledige overzicht.",
"See your progress": "Bekijk je voortgang",
"Scan complete": "Scan voltooid",
"Written in plain language, because you cannot consent to something you cannot read. Last updated {0}.": "Geschreven in eenvoudige taal, omdat je niet kunt instemmen met iets wat je niet kunt begrijpen. Laatst bijgewerkt {0}.",
"Back": "Terug",
"Who is responsible": "Wie is verantwoordelijk",
"Brigvanti is the controller of your personal data under the GDPR.": "Brigvanti is verantwoordelijk voor de verwerking van je persoonsgegevens onder de AVG.",
"The Ninth Tee, Rijswijkstraat 199, 1062 XL Amsterdam, the Netherlands. Chamber of Commerce number 98566903. Questions and requests: <b>legal@theninthtee.eu</b>.": "The Ninth Tee, Rijswijkstraat 199, 1062 XL Amsterdam, Nederland. Kamer van Koophandel nummer 98566903. Vragen en verzoeken: <b>legal@theninthtee.eu</b>.",
"What this pilot is": "Wat deze pilot inhoudt",
"Brigvanti is a learning tool. It shows you an advisory picture of your AI skills and gives you assignments to practise on.": "Brigvanti is een AI-blended leerapp. Het geeft je inzicht in je AI-vaardigheden en opdrachten om mee te oefenen.",
"It is not an assessment, a qualification or an exam. Your level is advice you may disagree with. It is never shared with an employer by us, and it never decides anything about you on its own. No decision with a legal or similar effect is made automatically.": "Het is geen beoordeling, geen kwalificatie of een examen. Jouw niveau is een inzicht waar je het misschien niet mee eens bent. Je profiel wordt nooit door ons gedeeld met een werkgever en de AI neemt nooit zelf een beslissing over jou. Er worden geen geautomatiseerde beslissingen genomen die impact hebben op jouw baan of een juridisch of vergelijkbaar effect hebben.",
"What we collect": "Wat we verzamelen",
"Only what the pilot needs to work.": "Alleen wat de pilot nodig heeft om te werken.",
"Your email address, or the account you sign in with": "Je e-mailadres, of het account waarmee je inlogt",
"Your first name, if you give one": "Je voornaam, als je die opgeeft",
"Your setup answers: role or ambition, and chosen topics": "Opbouw persoonlijk profiel: rol of ambitie, en gekozen onderwerpen",
"Your scan answers, and the level each skill is placed at": "Je scan antwoorden, en het niveau waarop elke vaardigheid wordt ingeschat",
"The text you write in a practice assignment, and the coach reply": "De tekst die je in een oefenopdracht schrijft, en de terugkoppeling van de AI-coach",
"Your badges, streak and assignment history": "Je badges, streak en opdrachtgeschiedenis",
"Your portfolio: the text of each assignment you hand in, the coach reply, and what you wrote when you claimed a level": "Je portfolio: de tekst van elke opdracht die je inlevert, het antwoord van de AI-coach, en wat je schreef toen je een niveau claimde",
"We ask you not to enter special category data. That means health details, political or religious views, trade union membership, ethnic origin, sexual orientation, or biometric and genetic data. We also ask you not to enter identification numbers, bank details, or another person's personal data. The app repeats this warning at every point where you type.": "We vragen je geen speciale persoonlijke informatie in te voeren. Dat betekent gezondheidsgegevens, politieke of religieuze opvattingen, vakbondslidmaatschap, etnische afkomst, seksuele geaardheid of biometrische en genetische gegevens. We vragen je ook niet om identificatienummers, bankgegevens of persoonlijke gegevens van een ander in te voeren. De app herhaalt deze waarschuwing op elk punt waar je tekst invoert.",
"Where your data goes": "Waar je data naartoe gaat",
"Read this part carefully, because it is the part people assume wrongly.": "Lees dit deel zorgvuldig, want het is het deel dat gebruikers niet altijd begrijpen.",
"<b>Stored data.</b> Your account, progress and assignment history are stored by Google Firebase. We use European region storage where the service offers it. Google may still process some data outside the European Economic Area under the European Commission's standard contractual clauses.": "<b>Opgeslagen gegevens.</b> Je account, voortgang en opdrachtgeschiedenis worden opgeslagen door Google Firebase. Waar de dienst dat aanbiedt, gebruiken we opslag in de Europese regio. Google kan sommige gegevens nog steeds buiten de Europese Economische Ruimte verwerken, op basis van de standaardcontractbepalingen van de Europese Commissie.",
"<b>Coach replies.</b> When you press send, the text you wrote in the assignment is sent to Anthropic, which provides the AI model behind the coach. <b>This processing is not limited to the European Economic Area.</b> It is covered by a data processing agreement and standard contractual clauses. If you would rather not have your text leave the platform, do not use the coach.": "<b>Antwoorden AI-coach.</b> Wanneer je op verzenden drukt, wordt de tekst die je in de opdracht hebt geschreven naar Anthropic gestuurd, dat het AI-model achter de AI-coach levert. <b>Deze verwerking is niet beperkt tot de Europese Economische Ruimte.</b> Het wordt gedekt door een gegevensverwerkingsovereenkomst en standaard contractuele clausules. Als je liever niet wilt dat je tekst het platform verlaat, gebruik dan de AI-coach niet.",
"<b>Hosting.</b> The site is served by Netlify and its code is held on GitHub. Netlify records technical request logs, including your IP address, to deliver and secure the site.": "<b>Hosting.</b> De site wordt gehost door Netlify en de code wordt opgeslagen op GitHub. Netlify registreert technische verzoeklogboeken, inclusief je IP-adres, om de site te leveren en te beveiligen.",
"We do not sell your data. We do not use it for advertising. We do not use your assignment text to train any AI model.": "Wij verkopen geen persoonlijke gegevens. Wij gebruiken jouw gegevens niet voor reclame. Wij gebruiken je opdrachttekst niet om het AI-model te trainen.",
"Why we are allowed to hold it": "Waarom we jouw data mogen bewaren",
"<b>Consent</b> for running the scan, storing your progress, and sending your text to the coach. You may withdraw it at any time, and withdrawing does not affect what happened before.": "<b>Toestemming</b> voor het uitvoeren van de scan, het opslaan van je voortgang en het versturen van je tekst naar de coach. Je kunt deze op elk moment intrekken; het intrekken heeft geen invloed op wat daarvoor is gebeurd.",
"<b>Legitimate interest</b> for keeping the service secure and working, and for improving the questions using data that no longer identifies you.": "<b>Legitiem belang</b> om de dienst veilig en werkend te houden, en om de vragen te verbeteren met data die niet langer terug te herleiden is naar jou als persoon.",
"Your portfolio": "Je portfolio",
"Your portfolio is the record of what you made. It holds the text you wrote in each assignment, the coach reply, and the note you added when you claimed a level.": "Je portfolio is het verslag van wat je hebt gemaakt. Het bevat de tekst die je bij elke opdracht hebt geschreven, het antwoord van de AI-coach en de notities toen je een level claimde.",
"It exists for one reason, which is so you can find your own work again and see how it changed. Nobody at Brigvanti reviews it, scores it, or checks whether a level you claimed was deserved. It is not shared with an employer by us.": "Dit hulpmiddel is er puur voor jou, om je eigen werk terug te vinden en de verandering ervan te volgen. Brigvanti beoordeelt je werk niet en controleert niet of een geclaimd niveau klopt. Je gegevens worden nooit met een werkgever gedeeld door ons.",
"It is stored with the rest of your account in Firebase, and a copy is held on this device so the app works when you are offline. You can download the whole portfolio as a spreadsheet at any time from Your progress.": "Het wordt met de rest van je account opgeslagen in Firebase. Er staat ook een kopie op dit apparaat, zodat de app offline werkt. Je kunt het hele portfolio altijd als spreadsheet downloaden bij 'Je voortgang'.",
"Because it holds text you wrote yourself, it is the part of your account most likely to contain something personal. That is why we ask you not to enter private details, and why you can erase all of it in one action.": "Omdat hier teksten staan die je zelf hebt geschreven, is dit het deel van je account waarin de meeste persoonlijke informatie kan staan. Daarom vragen we je om geen privégegevens in te vullen, en kun je alles in één keer wissen.",
"How long we keep it": "Hoe lang bewaren we jouw data",
"Your account data is kept while your account is open. When you delete your account or reset the pilot, we delete it from our storage straight away. Our storage provider, Google Firebase, completes the deletion from its systems and backups within 180 days. Netlify keeps technical logs with your IP address for up to 90 days, and archived copies for up to one year.": "Je accountgegevens bewaren we zolang je account actief is. Verwijder je je account of reset je de pilot, dan wissen we ze direct uit onze opslag. Onze opslagdienst, Google Firebase, rondt het wissen in zijn systemen en back-ups binnen 180 dagen af. Netlify bewaart technische logboeken met je IP-adres tot 90 dagen, en gearchiveerde kopieën tot een jaar.",
"You can erase everything yourself at any time. Open Your progress and choose Reset this pilot. That deletes your levels, badges, streak and your whole portfolio, from this device and from our storage. We remove the server copy first, and confirm it to you. If that step fails, we tell you rather than pretending it worked.": "Je kunt altijd zelf alles wissen. Ga naar 'Je voortgang' en kies 'Reset deze pilot'. Dit verwijdert je niveaus, badges, streak en je hele portfolio van dit apparaat én van onze server. We wissen eerst de serverkopie en bevestigen dit aan jou. Mocht dit mislukken, dan melden we dat eerlijk in plaats van te doen alsof het gelukt is.",
"Deletion is permanent. Download your record first if you want to keep it.": "Verwijdering is permanent. Download eerst je dossier als je je data wilt bewaren.",
"Your rights": "Je rechten",
"You can ask to see your data, correct it, erase it, restrict how it is used, object to its use, or receive a copy to take elsewhere. Write to <b>legal@theninthtee.eu</b> and we answer within one month.": "Je kunt vragen om je gegevens in te zien, te corrigeren, te wissen, het gebruik te beperken, bezwaar te maken tegen het gebruik ervan, of een kopie te ontvangen om mee te nemen naar een andere dienst. Schrijf naar <b>legal@theninthtee.eu</b>, dan beantwoorden we je verzoek binnen een maand.",
"You can also download your own record at any time from Your progress.": "Je kunt ook op elk moment je eigen data downloaden in Je voortgang.",
"If you are not satisfied, you may complain to the Dutch data protection authority, the Autoriteit Persoonsgegevens.": "Als je niet tevreden bent, kun je een klacht indienen bij de Nederlandse Autoriteit Persoonsgegevens.",
"Cookies and analytics": "Cookies en analytics",
"We use only what is needed to keep you signed in and to keep the service secure. We do not set advertising or tracking cookies of our own.": "We gebruiken alleen gegevens die nodig zijn om je ingelogd te houden en de app veilig te houden. We plaatsen zelf geen cookies voor advertenties of tracking.",
"Usage analytics stay off unless you allow them. If you allow them, we use Google Analytics to collect anonymous usage data, so we can improve Brigvanti. Google Analytics sets a cookie named _ga and sends usage data to Google, including outside the European Economic Area under the European Commission's standard contractual clauses. We keep Google's advertising and personalisation features switched off, so this is analytics only. Nothing from Google loads or is collected until you allow it. You can turn it off again at any time here, which stops the collection and clears its cookie.": "Analytische gegevens staan standaard uit. Geef je toestemming, dan gebruiken we Google Analytics om anonieme gebruiksgegevens te verzamelen om Brigvanti te verbeteren. Google Analytics plaatst een _ga-cookie en stuurt gegevens naar Google (ook buiten de EER via goedgekeurde EU-modelcontracten). Omdat we advertentie- en personalisatiefuncties hebben uitgeschakeld, worden er puur statistieken verzameld. Er wordt pas iets geladen of verzameld ná jouw toestemming. Je kunt dit altijd weer uitzetten; het verzamelen stopt dan direct en de cookie wordt gewist.",
"Allow analytics": "Toestaan van analytics",
"Turn analytics off": "Zet analytics uit",
"Status: analytics allowed.": "Status: analytics toegestaan.",
"Status: analytics off.": "Status: analytics uit.",
"Status: not chosen yet, so analytics are off.": "Status: nog niet gekozen, dus de analytics staan uit.",
"Age": "Leeftijd",
"This pilot is for adults. You must be 18 or over to take part.": "Deze pilot is voor volwassenen. Je moet 18 jaar of ouder zijn om mee te doen.",
"Using the pilot": "Gebruik van de pilot",
"This is a pilot, so things can change or break. We give no warranty that it is free of errors.": "Dit is een pilot, dus functies kunnen veranderen of niet werken. We geven geen garantie dat de tool geen fouten bevat.",
"The coach gives suggestions, not professional advice. Do not rely on it for legal, medical, financial or safety decisions. You stay responsible for what you send, publish or act on.": "De AI-coach geeft suggesties, geen professioneel advies. Vertrouw er niet op voor juridische, medische, financiële of veiligheidsbeslissingen. Je blijft verantwoordelijk voor wat je verstuurt, publiceert of hoe je er naar handelt.",
"You keep ownership of the text you write. You give us permission to process it in order to give you feedback and to show you your own record.": "Je behoudt het eigendom van de tekst die je schrijft. Je geeft ons toestemming om deze te verwerken om je feedback te geven en jou je eigen verslag te laten zien.",
"The framework, questions and assignments are owned by Brigvanti. Please do not copy or redistribute them.": "Het framework, de vragen en opdrachten zijn eigendom van Brigvanti. Kopiëren of verspreiden is niet toegestaan.",
"Reporting a problem": "Een probleem melden",
"If something looks wrong, unfair or unsafe, tell us at <b>legal@theninthtee.eu</b>. Feedback on a placement is welcome, and a placement you disagree with is useful information for us.": "Als er iets verkeerd, oneerlijk of onveilig uitziet, laat het ons dan <b>legal@theninthtee.eu</b> weten. Feedback over de tool is welkom, alle feedback is nuttige informatie voor ons.",
"Everything you build here is kept, so you can look back and see how your work changed.": "Alles wat je hier bouwt, wordt bewaard, zodat je kunt terugkijken en zien hoe je werk is veranderd.",
"Nothing in it yet. Hand in your first assignment and it appears here.": "Je hebt nog geen inhoud. Lever je eerste opdracht in, zodra de opdracht is ingeleverd dan kun je deze hier terugvinden.",
"Practise on real tasks": "Oefenen op echte taken",
"{0} piece": "{0} opdracht",
"{0} pieces": "{0} opdrachten",
"level earned": "Behaald niveau",
"From {0} to {1}": "Van {0} naar {1}",
"Everything you made, kept in order. Open a skill to see how your work changed over time.": "Alles wat je hebt gemaakt, is gearchiveerd. Open een vaardigheid om te zien hoe je vaardigheid in de loop van de tijd is veranderd.",
"This is yours": "Dit is van jou",
"Nobody reviews it and nobody scores it. It is here so you can find your work again, see your own progress, and show it if you ever want to.": "Niemand evalueert het en niemand beoordeelt het. Het is hier opgeslagen zodat je je input weer kunt vinden, je eigen voortgang kunt zien en het kunt laten zien aan anderen.",
"Download all my work": "Download al mijn werk",
"Piece {0}": "Stuk {0}",
"The prompt you wrote": "De prompt die je schreef",
"What came back": "Wat terugkwam",
"What you did with it": "Wat je ermee hebt gedaan",
"What you noticed": "Wat je hebt opgemerkt",
"Your coach said": "Je AI-coach zei",
"How your prompts changed": "Hoe je prompts veranderden",
"Your first and your most recent, side by side. This is the clearest picture of your own progress.": "Je eerste en meest recente, naast elkaar. Dit is het duidelijkste beeld van je eigen vooruitgang.",
"First, {0}": "Ten eerste, {0}",
"Most recent, {0}": "Het meest recente, {0}",
"Level earned, {0}": "Verdiend niveau, {0}",
"Confirmed on {0}.": "Bevestigd op {0}.",
"What you made": "Wat je hebt gemaakt",
"What changed": "Wat is er veranderd",
"No assignments handed in for this skill yet.": "Er zijn nog geen opdrachten ingeleverd voor deze vaardigheid.",
"2. What came back, or what you found": "2. Wat terugkwam, of wat je vond",
"2. Paste what the tool gave back": "2. Plak wat je AI-tool heeft teruggekoppeld",
"If you did not use an AI tool, describe what you found or decided instead.": "Als je geen AI-tool hebt gebruikt, beschrijf dan wat je hebt gevonden of hebt besloten.",
"You used a prompt, so paste the real answer. Your coach can only judge the wording if it sees it. A long reply can be trimmed.": "Je hebt een prompt gebruikt, plak het antwoord van je AI-tool hier in. Je AI-coach kan alleen de bewoording beoordelen zodra de tekst is ontvangen. Een lang antwoord kan worden ingekort.",
"Type what you found, checked or decided": "Typ wat je hebt gevonden, gecontroleerd of besloten hebt",
"Paste the reply exactly as you received it": "Plak het antwoord precies zoals je het hebt ontvangen",
"Got it": "Begrepen",
"You filled in a prompt, so box 2 needs the answer you actually received. Paste it in rather than describing it, so your coach can judge the real wording.": "Je hebt een prompt ingevuld, plak het antwoord dat je hebt ontvangen in box 2. Plak het erin in plaats van het te beschrijven, zodat je AI-coach de echte bewoording kan beoordelen.",
"Your role asks for": "Je rol vraagt om",
"You are aiming for": "Je mikt op",
"For example, I want to check whether an article I was sent is trustworthy": "Ik wil bijvoorbeeld controleren of een artikel dat mij is toegestuurd betrouwbaar is",
"For example, I need to write a reply to a supplier chasing an invoice I already paid": "Ik moet bijvoorbeeld een antwoord schrijven aan een leverancier over een factuur die ik al betaald heb",
"For example, I have a long email thread from this week I still need to catch up on": "Ik heb bijvoorbeeld een lange e-mailthread van deze week die ik nog moet lezen",
"For example, I want to understand my energy bill and check whether a figure is right": "Ik wil bijvoorbeeld mijn energierekening begrijpen en controleren of het verbruik en de bijbehorende kosten met elkaar overeenkomen",
"For example, I retype the same weekly message every Monday": "Bijvoorbeeld, ik typ elke maandag hetzelfde wekelijkse bericht opnieuw",
"For example, I want to send a document to a colleague but it holds personal details": "Bijvoorbeeld, ik wil een document naar een collega sturen, maar het bevat persoonlijke gegevens",
"For example, my father keeps asking me how to use AI on his phone": "Bijvoorbeeld, mijn vader blijft me vragen hoe ik AI op zijn telefoon kan gebruiken",
"Describe the task you actually have this week": "Beschrijf de taak die je deze week daadwerkelijk hebt",
"Not scanned yet. Tap to start this area.": "Nog niet gescand. Kies om dit gebied te starten.",
"{0} of {1} skills placed. Tap to continue.": "{0} van {1} vaardigheden geplaatst. Kies om door te gaan.",
"{0} {1}. {2} level to grow.": "{0} {1}. Nog {2} niveau te gaan.",
"{0} {1}. {2} levels to grow.": "{0} {1}. Nog {2} niveaus te gaan.",
"You are at or above what you are aiming for.": "Je zit op of boven het niveau wat je nastreeft.",
"Where you stand at the moment": "Waar je nu staat",
"A mirror, not a verdict. It moves as you practise. Tap any area to scan or continue it.": "Een persoonlijk inzicht, geen oordeel. Het verbetert terwijl je oefent. Kies elk gebied om te scannen of ga door met het huidige gebied.",
"Where you judged yourself differently": "Waar je jezelf anders op inschatte",
"You picked a higher statement than the questions showed. That is normal and useful.": "Je schatte jezelf hoger in dan je antwoorden laten zien. Dat is normaal en het inzicht nuttig.",
"You chose {0}. Placed at {1}.": "Je hebt {0} gekozen. Geplaatst op {1}.",
"Where practice pays off most": "Waar oefenen het meeste oplevert",
"Choose the area you want to practise now.": "Kies het gebied waar je nu wilt oefenen.",
"{0} now. {1} {2}.": "Nu {0}. {1} {2}.",
"Your profile": "Jouw profiel",
"All areas": "Alle gebieden",
"{0} done": "{0} gedaan",
"None of these fit my week": "Geen van deze opdrachten past bij mijn huidige werkweek",
"Describe a task you actually have, and your coach builds the assignment around it.": "Beschrijf een taak die je daadwerkelijk hebt, en je AI-coach creert de opdracht op basis van jouw ingegeven taak.",
"You are practising <b>{0}</b>. Pick something you actually have to do this week.": "Je oefent <b>{0}</b>. Kies iets wat je deze week echt moet doen.",
"Pick something you actually have to do this week. The assignment is the task itself.": "Kies iets wat je deze week echt moet doen. De opdracht is de taak zelf.",
"{0} day streak": "{0} dagstreak",
"{0} assignment handed in. You earn this by doing real work.": "{0} opdracht ingeleverd. Je verdient dit door echte taken uit te voeren.",
"{0} assignments handed in. You earn this by doing real work.": "{0} opdrachten ingeleverd. Je verdient dit door echte taken uit te voeren.",
"No ready made tasks for this area yet. Use the option above to describe your own.": "Nog geen kant-en-klare taken voor dit gebied. Gebruik de bovenstaande optie om je eigen taken te beschrijven.",
"Place at least one area in the scan first.": "Voltooi eerst minstens één gebied in de scan.",
"Your own task": "Je eigen taak",
"Your choice": "Jouw keuze",
"<b>You are working towards {0} in {1}.</b> At this level someone {2}": "<b>Je werkt aan {0} in {1}.</b> Iemand op dit niveau {2}",
"Step 1 of 3": "Stap 1 van 3",
"Describe the real task you have": "Beschrijf de echte taak die je hebt",
"Do not solve it yet, and do not explain anything. Just tell your coach what you actually need to get done. It will turn that into a short assignment for you.": "Los het nog niet op en leg niets uit. Vertel je AI-coach gewoon wat je echt moet doen. De AI-coach maakt een korte opdracht voor je.",
"Building your assignment": "Je opdracht wordt gecreerd",
"Build my assignment": "Creer mijn opdracht",
"Practice assignment": "Oefenopdracht",
"Paste the exact words you typed": "Plak precies de woorden die je hebt getypt",
"For example, I checked the date on the official site and it was wrong, so I corrected it before sending": "Bijvoorbeeld, ik heb de datum op de officiële site gecontroleerd en die was fout, dus heb ik het gecorrigeerd voordat ik het verstuurde",
"Step 2 of 3": "Stap 2 van 3",
"Learn": "Leer",
"Now do this for real": "Doe dit nu echt",
"A strong attempt shows": "Een sterke poging toont zich",
"Step 3 of 3": "Stap 3 van 3",
"Hand in what you made": "Lever in wat je hebt gemaakt",
"Three short boxes. Remove anything private first.": "Drie korte keuzes. Verwijder eerst alles privé.",
"1. The prompt you used": "1. De prompt die je gebruikte",
"(optional)": "(optioneel)",
"Leave this empty if you did not use an AI tool.": "Laat dit leeg als je geen AI-tool hebt gebruikt.",
"3. What you did with it, and what you noticed": "3. Wat je ermee hebt gedaan, en wat je hebt opgemerkt",
"What you changed, checked or sent, and what stood out.": "Wat je veranderde, controleerde of stuurde, en wat opviel.",
"Your coach is reading": "Je AI-coach leest",
"Send to my coach": "Stuur naar mijn AI-coach",
"One or two lines": "Eén of twee lijnen",
"Your coach": "Je AI-coach",
"Hand in this assignment": "Lever deze opdracht in",
"What did you notice?": "Wat viel je op?",
"Handed in": "Ingeleverd",
"{0} day streak. That is assignment {1} on this skill.": "{0} dagstreak. Dat is opdracht {1} op deze vaardigheid.",
"Another assignment": "Nog een opdracht",
"Come back around <b>{0}</b> for the next one. It will be a little harder. Spacing is what turns this into a habit.": "Kom terug rond <b>{0}</b> voor de volgende. De volgende taak wordt wat moeilijker. Een tussenpauze nemen en herhalen is hoe je gewoontes kan bouwen.",
"Try the level up test": "Probeer de level up-test",
"Please write one full sentence about the real task.": "Schrijf alsjeblieft één volledige zin over de echte taak.",
"Your coach could not be reached. Check your connection and try again.": "Je AI-coach was niet bereikbaar. Controleer je verbinding en probeer het opnieuw.",
"You used a prompt, so please paste the real answer in box 2. Your coach needs the actual wording to give useful feedback.": "Je hebt een prompt gebruikt, dus plak alsjeblieft het echte antwoord in box 2. Je AI-coach heeft de daadwerkelijke text en context nodig om nuttige feedback te geven.",
"Please fill in box 2 or box 3 before sending. Box 1 is optional.": "Vul box 2 of box 3 in voordat je het verstuurt. Box 1 is optioneel.",
"Your coach could not be reached. Your work is safe. Please try again.": "Je AI-coach was niet bereikbaar. Je werk is veilig. Probeer het alsjeblieft opnieuw.",
"A level up test opens once you have scanned an area and practised its skills.": "Een level-up test opent zodra je een gebied hebt gescand en de vaardigheden hebt geoefend.",
"Scan an area, then hand in a practice task. The test then asks you to show the level in two ways, and one of them is a real task.": "Scan een gebied en lever dan een oefenopdracht in. De test vraagt je vervolgens het niveau op twee manieren te tonen, waarvan één een echte taak is.",
"Pick an area, then a skill that is ready. Both parts of the test must be clear. Questions are checked against a fixed answer key. The real task you confirm yourself. Your coach decides neither.": "Kies een gebied, daarna een vaardigheid die klaar is. Beide onderdelen van de test moeten duidelijk zijn. Vragen worden gecontroleerd aan de hand van een vaste antwoordcode. De echte taak bevestig je zelf. Je AI-coach beslist niet of je het gehaald hebt of niet, dit is je eigen verantwoordelijkheid en inzicht.",
"{0} skill ready to test": "{0} vaardigheid klaar om getest te worden",
"{0} skills ready to test": "{0} vaardigheden klaar om te testen",
"Practise a skill to open a test": "Oefen een vaardigheid om een test te openen",
"{0} ready": "{0} klaar",
"in progress": "In uitvoering",
"at your target": "Bij je doel",
"nothing higher to test": "Niets hoger om te testen",
"test to {0}": "test voor {0}",
"{0} of {1} practised": "{0} van {1} geoefend",
"Practise {0} more to open the test.": "Oefen {0} meer om de test te openen.",
"Tap a skill that is ready to take its level up test. The rest open as you practise.": "Kies een vaardigheid die klaar is om een level-up test te maken. De rest is beschikbaar terwijl je oefent.",
"No placed skills in this area yet.": "Geen gescande vaardigheden in dit gebied.",
"Grow {0}": "Groei {0}",
"Two ways to grow": "Twee manieren om te groeien",
"Practise on a real task to sharpen a skill. When a skill has enough practice behind it, its level up test opens.": "Oefen op een echte taak om een vaardigheid te verfijnen. Wanneer een vaardigheid genoeg geoefend is, dan wordt de level-up test beschikbaar.",
"You are at {0} here.": "Je bent hier {0}.",
"{0} {1}, {2} level to grow.": "{0} {1}, nog {2} niveau te gaan.",
"{0} {1}, {2} levels to grow.": "{0} {1}, nog {2} niveaus te gaan.",
"Level up, {0} ready": "Level up, {0} klaar",
"Level up, practise first to open a test": "Level op, oefen eerst om een test te openen",
"Grow": "Groei",
"Part 1 of 2. Question {0} of {1}. Both must be correct.": "Deel 1 van 2. Vraag {0} van {1}. Beide moeten correct zijn.",
"Level up test": "Level up-test",
"Not this time, and that is fine": "Deze keer niet, en dat is prima",
"Part 1 asks you to recognise the right move at this level, including on a question you have never seen. One answer did not hold.": "Deel 1 vraagt je om de juiste zet op dit niveau te herkennen, ook bij een vraag die je nog nooit hebt gezien. Eén antwoord hield niet stand.",
"Nothing is lost and nothing is recorded against you. Do another assignment or two, then come back.": "Er gaat niets verloren en er wordt niets in je nadeel geregistreerd. Doe gerust nog een opdracht of twee en kom daarna weer terug.",
"Do another assignment": "Doe een andere opdracht",
"For example: My weekly team update used to take an hour. I built a prompt that turns my rough notes into our standard format, saved it in my notes app, and Monday's update went out to the team using it.": "Een voorbeeld: Vroeger kostte de wekelijkse teamupdate me een uur. Nu gebruik ik een vaste prompt in mijn notities-app die mijn ruwe aantekeningen direct in het juiste format zet. De update van afgelopen maandag stond er zo in.",
"For example: I reuse this now instead of rewriting it each week.": "Bijvoorbeeld: ik gebruik dit nu opnieuw in plaats van het elke week opnieuw te schrijven.",
"Part 1 is clear": "Deel 1 is duidelijk",
"Part 2. Do it for real": "Deel 2. Doe het echt",
"Do one real task in your own life or work. Tick every point below that you actually did. You need all of them ticked to claim the level. At this level you confirm your own work, the coach does not.": "Voer één echte taak uit in je eigen leven of werk. Vink hieronder elk punt aan dat je daadwerkelijk hebt gedaan. Je moet ze allemaal aanvinken om dit niveau te claimen. Op dit niveau bevestig je je eigen werk; de AI-coach doet dat niet.",
"Add it to your portfolio": "Voeg het toe aan je portfolio",
"Now write your evidence in one or two sentences, in plain words. Cover the three things below, so you and others can find it and see what you did. It is never graded.": "Omschrijf je bewijs in één of twee eenvoudige zinnen. Behandel de drie onderstaande punten, zodat jij en anderen direct kunnen zien wat je hebt gedaan. Je krijgt hier nooit een cijfer voor.",
"What the real task was": "Wat de echte taak was",
"What you actually produced": "Wat je daadwerkelijk hebt gedaan",
"Where it lives now, or who received it": "Waar het nu staat, of wie het heeft ontvangen",
"Later you may want to show this, or simply find it again.": "Misschien dat je dit later wilt delen, of opnieuw opzoeken.",
"What changed in how you work? Optional, one line.": "Wat is er veranderd in je werkwijze? Optioneel, één regel.",
"Confirm and claim the level": "Bevestig en claim het niveau",
"Nobody checks this. The level is yours. An honest one is worth more than a high one, because only an honest one tells you what to practise next.": "Niemand controleert dit; het is jouw niveau. Een eerlijke inschatting is meer waard dan een te hoge, want alleen een eerlijk niveau laat zien wat je daarna nog moet oefenen.",
"You reached {0}": "Je hebt {0} behaald",
"You answered a question you had never seen, and you confirmed a real task against fixed points. {0} now sits at {1}.": "Je beantwoordde een vraag die je nog niet had gekregen, en je bevestigde een echte taak op basis van de vaste onderdelen. {0} zit nu op {1}.",
"Another level up": "Een hoger niveau behaald",
"Tick every point above. {0} still need confirming.": "Vink elk punt hierboven aan. Er moeten er nog {0} bevestigd worden.",
"Add your evidence, one or two sentences.": "Voeg je bewijs toe, één of twee zinnen.",
"All set. You can claim the level.": "Alles klaar. Je kunt het level claimen.",
"Every point must be true. If one is not, do the task again. That is the point of the level.": "Elk punt moet waar zijn. Als dat niet zo is, doe de taak dan opnieuw. Dat is het doel van het level.",
"Please cover all three points, so your evidence can be found and understood later.": "Behandel alsjeblieft alle drie de punten, zodat je bewijs later gevonden en begrepen kan worden.",
"{0} has moved up to {1}.": "{0} is opgeklommen naar {1}.",
"{0} assignment": "{0} opdracht",
"{0} assignments": "{0} opdrachten",
"Your skills": "Jouw vaardigheden",
"Every skill you have placed, with its level.": "Elke vaardigheid die je hebt geplaatst, met het niveau ervan.",
"Nothing placed yet. Scan an area from Your progress to begin.": "Nog niets getoetst. Scan een gebied vanuit Je voortgang om te beginnen.",
"What you have built so far. It grows every time you hand something in.": "Wat je tot nu toe hebt opgebouwd. Het groeit elke keer dat je iets inlevert.",
"Effort points": "Inspanningspunten",
"Earned by handing in work and levelling up, never by being right.": "Verdiend door werk in te leveren en te levelen, nooit door gelijk te hebben.",
"day streak": "Dagstreak",
"assignments handed in": "Ingeleverde opdrachten",
"skills placed": "Vaardigheden geplaatst",
"levels earned": "Behaalde levels",
"badges earned": "Behaalde badges",
"skills in total": "Vaardigheden in totaal",
"Your AI-literacy level": "Jouw AI-geletterdheidsniveau",
"tap an area to scan or practise ▾": "Tik op een gebied om te scannen of te oefenen ▾",
"A mirror, not a verdict. It moves as you practise.": "Een inzicht, geen oordeel. Het wordt sterker terwijl je oefent.",
"Tap to open your portfolio ›": "Tik om je portfolio te openen ›",
"Your badges": "Jouw badges",
"{0} of {1} earned ▾": "{0} van {1} verdiend ▾",
"Every one of them is for doing something real.": "Elk van hen is bedoeld omdat je echt hebt geoefend.",
"Assignments": "Toewijzingen",
"Download my work": "Download mijn werk",
"Download record": "Download record",
"Privacy & legal": "Privacy & juridisch",
"Log out": "Uitloggen",
"Account settings": "Accountinstellingen",
"{0} pilot check for the Brigvanti team": "{0} pilootcontrole voor het Brigvanti-team",
"Reset pilot": "Reset piloot",
"Pilot only. Both controls above are removed in the live version.": "Alleen pilot. Beide bovenstaande besturingen zijn verwijderd in de live versie.",
"Not placed yet. Scan an area to begin.": "Nog niet geplaatst. Scan een gebied om te beginnen.",
"Across {0} placed skill. Tap for the breakdown.": "Over {0} geplaatste vaardigheid. Kies voor de samenvatting.",
"Across {0} placed skills. Tap for the breakdown.": "Over {0} geplaatste vaardigheden. Kies voor de samenvatting.",
"{0} skill ready for a level-up test.": "{0} vaardigheid klaar voor een level-up test.",
"{0} skills ready for a level-up test.": "{0} vaardigheden klaar voor een level-up test.",
"{0} piece of your own work, kept in order.": "{0} stuk van je eigen werk, netjes bijgehouden.",
"{0} pieces of your own work, kept in order.": "{0} stukjes van je eigen werk, netjes bijgehouden.",
"Your work appears here once you hand something in.": "Je werk verschijnt hier zodra je iets inlevert.",
"Hide": "Verbergen",
"Show": "Tonen",
"Erase everything?": "Alles wissen?",
"This deletes your levels, badges, streak and your whole portfolio, from this device and from our storage. It cannot be undone. Download your record first if you want to keep it.": "Dit verwijdert je levels, badges, streak en je hele portfolio van dit apparaat én uit onze opslag. Dit kan niet ongedaan worden gemaakt. Download eerst je record als je het wilt bewaren.",
"Erase everything": "Alles wissen",
"Keep it": "Toch behouden",
"G5 calibration": "G5-kalibratie",
"Not learner facing. Does the ladder behave like a ladder? At one tester this shows the read, not a verdict.": "Niet leerlinggericht. Gedraagt de ladder zich als een ladder? Bij een tester toont dit de leesopdracht, geen oordeel.",
"answers logged": "Bewaarde antwoorden",
"ladder reversals": "Ladder-omkeringen",
"This cannot see reasoning. A lucky guess and sound judgement both read the same. That is what G4 is for.": "Dit is geen logische redenering. Een geluk en een goed oordeel lezen allebei hetzelfde. Daar is G4 voor.",
"{0} answered": "{0} beantwoord",
"Answer across at least two levels to read the ordering.": "Beantwoord minstens twee niveaus om de volgorde te lezen.",
"Ordering holds. Difficulty rises with the level.": "De moeilijkheid neemt toe met het niveau.",
"Ordering breaks. A higher level came out easier. Route back to G0 or G2.": "Een hoger niveau kwam makkelijker naar buiten. Route terug naar G0 of G2.",
"Assignment": "Toewijzing",
"The task you set": "De taak die je opgeeft",
"The assignment": "De opdracht",
"Your prompt": "Jouw prompt",
"What the tool gave back": "Wat de tool teruggaf",
"What you did": "Wat je hebt gedaan",
"Your reflection": "Jouw spiegelbeeld",
"Level up · {0}": "Level up · {0}",
"What changed in how you work": "Wat is er veranderd in jouw werkwijze?",
"Brigvanti portfolio{0}": "Brigvanti-portfolio{0}",
"Everything you made, kept in order.": "Alles wat je hebt gemaakt, netjes bijgehouden.",
"Exported {0}. {1} piece.": "Geëxporteerd {0}. {1} stuk.",
"Exported {0}. {1} pieces.": "Geëxporteerd {0}. {1} stukken.",
"This is yours. Nobody reviews it and nobody scores it. It records the real work you did and what your coach said.": "Dit is van jou. Niemand beoordeelt het. Het registreert het echte werk dat je hebt gedaan en wat je AI-coach zei.",
"Brigvanti. Your coach advises, it never scores. This portfolio is not an assessment.": "Brigvanti. Je AI-coach adviseert en geeft geen cijfers. Dit portfolio is geen beoordeling.",
"Nothing handed in yet.": "Nog niets ingeleverd.",
"Welcome{0}": "Welkom{0}",
"This is your account page. Everything about you will live here.": "Dit is je accountpagina. Hier komt alles over jou te staan.",
"First, the scan": "Eerst de scan",
"Let us start with a short scan. After your first area, you can come back here and edit your account details.": "Laten we beginnen met een korte scan. Na je eerste onderdeel kun je hier terugkomen om je accountgegevens te bewerken.",
"Go to the scan": "Ga naar de scan",
"Assessed": "In kaart gebracht",
"Assess this area": "Scan dit onderdeel",
"Work and life": "Werk en leven",
"Not set": "Niet ingesteld",
"Your name": "Jouw naam",
"Save": "Opslaan",
"Edit name": "Naam bewerken",
"Google Sign-In": "Inloggen met Google",
"Connected": "Verbonden",
"Change password": "Wachtwoord wijzigen",
"A secure reset link is emailed to you": "Je ontvangt een beveiligde resetlink per e-mail.",
"Delete your account?": "Je account verwijderen?",
"This erases everything. It cannot be undone.": "Dit verwijderd alles. Dit kan niet ongedaan worden gemaakt.",
"Delete": "Verwijderen",
"Delete my account": "Verwijder mijn account",
"Erase everything, permanently": "Verwijder alles, voorgoed",
"Toggle reminders": "Herinneringen",
"Personal": "Persoonlijk",
"Email": "E-mail",
"Your focus": "Jouw focus",
"Security": "Beveiliging",
"Notifications": "Meldingen",
"Reminders": "Herinneringen",
"Nudges on your come-back days. Live soon.": "Nudges op je comeback-dagen.",
"Language": "Taal",
"Subscription": "Abonnement",
"Current plan": "Huidig plan",
"Free": "Gratis",
"Your areas": "Jouw onderdelen",
"Areas": "Onderdelen",
"Pick an area to assess, or continue where you left off.": "Kies een onderdeel om te scannen, of ga verder waar je gebleven was.",
"Continue the scan": "Ga verder met de scan",
"Connecting...": "Verbinden...",
"You are leaving the app": "Je verlaat de app",
"Do you want to leave?": "Wil je weggaan?",
"No, stay": "Nee, blijf",
"Yes, leave": "Ja, ga weg",
"Customer-contact agent": "Klantcontactagent",
"Workforce planner / analyst": "Workforce planner / analist",
"Knowledge worker (generalist)": "Kenniswerker (generalist)",
"Team lead / people manager": "Teamleider / people manager",
"AI champion / change & L&D lead": "AI-kampioen / verandering & L&D-leider",
"Senior leader / director": "Senior leider / directeur",
"Administrative / clerical worker (P1)": "Administratief / administratief medewerker (P1)",
"Marketing / advertising professional (P2)": "Marketing- / reclameprofessional (P2)",
"Healthcare professional, nurse/clinician (P2)": "Zorgprofessional, verpleegkundige/behandelaar (P2)",
"Hospitality front-office agent (P1)": "Hospitality frontoffice-agent (P1)",
"Hospitality revenue manager (P2)": "Hospitality revenue manager (P2)",
"Email & messages": "E-mail & berichten",
"Web research & fact-checking": "Webonderzoek en feitencontrole",
"Personal finance & budgeting": "Persoonlijke financiën & budgettering",
"Meal planning & cooking": "Maaltijdplanning en koken",
"Travel planning": "Reisplanning",
"Photos & files": "Foto's & bestanden",
"Health & wellbeing info": "Informatie over gezondheid en welzijn",
"Learning & study": "Leren en studeren",
"Home admin & documents": "Thuisadministratie & documenten",
"Helping & leading others": "Anderen helpen en leiden",
"Draft a reply with AI": "Stel een antwoord op met AI",
"Summarise a long thread or chain": "Vat een lange draad of ketting samen",
"Triage the inbox by priority": "Triage de inbox op prioriteit",
"Check a claim or request before acting on it": "Controleer een claim of verzoek voordat je er iets mee doet",
"Spot a phishing or manipulative message": "Herken een phishing- of manipulatieve boodschap",
"Keep a review step before an AI message is sent": "Houd een beoordelingsstap voordat er een AI-bericht wordt verzonden",
"Look something up and judge if it is trustworthy": "Zoek iets op en beoordeel of het betrouwbaar is",
"Verify an AI answer before relying on it": "Verifieer een AI-antwoord voordat je erop vertrouwt",
"Ask a good research question": "Stel een goede onderzoeksvraag",
"Refine when the first answer misses": "Verfijn wanneer het eerste antwoord mist",
"Understand what the AI tool actually is and does": "Begrijp wat de AI-tool eigenlijk is en doet",
"Notice when an AI recommendation could be unfair": "Let op wanneer een AI-aanbeveling oneerlijk kan zijn",
"Read a chart or summary of your spending": "Lees een grafiek of samenvatting van je uitgaven",
"Verify an AI figure such as a rate or total": "Controleer een AI-cijfer, zoals een tarief of totaal.",
"Ask AI to explain a money concept simply": "Vraag AI om een geldconcept eenvoudig uit te leggen",
"Keep your own judgement on AI money advice": "Houd je eigen oordeel over AI-geldadvies",
"Automate a recurring money task like a bill reminder": "Automatiseer een terugkerende geldtaak, zoals een factuurherinnering",
"Get recipe ideas from what you have": "Haal receptideeën uit wat je hebt",
"Sanity-check an AI nutrition or quantity claim": "Controleer de verstandigheid van een AI-voedings- of hoeveelheidsclaim",
"Scale or convert a recipe and check it": "Schaal op of zet een recept om en controleer het",
"Save a meal-plan prompt to reuse weekly": "Sla een maaltijdplan-prompt op om wekelijks opnieuw te gebruiken",
"Plan an itinerary with real constraints": "Plan een reisroute met reële beperkingen",
"Verify hours, prices or visa info": "Controleer openingstijden, prijzen of visumgegevens",
"Compare options and decide for yourself": "Vergelijk opties en beslis zelf",
"Spot a too-good deal or travel scam": "Zie een te goede deal of reisoplichterij",
"Build a reusable trip-planning template": "Bouw een herbruikbare reisplanningstemplate",
"Organise, rename and find your files": "Organiseer, hernoem en vind je bestanden",
"Auto-sort photos by date or rule": "Sorteer foto's automatisch op datum of regel",
"Back up what matters": "Maak een back-up van wat belangrijk is",
"Think before uploading personal photos to a tool": "Denk na voordat je persoonlijke foto's uploadt naar een tool",
"Recognise an AI-edited or generated image": "Herken een door AI bewerkte of gegenereerde afbeelding",
"Decide if an app is trustworthy before giving it data": "Bepaal of een app betrouwbaar is voordat je hem gegevens geeft",
"Ask AI a health question and treat it carefully": "Stel AI een gezondheidsvraag en behandel die zorgvuldig",
"Verify a health claim against a reliable source": "Verifieer een gezondheidsclaim aan de hand van een betrouwbare bron",
"Keep a professional or human in the loop": "Houd een professional of mens op de hoogte",
"Protect sensitive health data when using AI": "Bescherm gevoelige gezondheidsgegevens bij het gebruik van AI",
"Get AI to explain a concept at your level": "Laat AI een concept op jouw niveau uitleggen",
"Refine an explanation until it clicks": "Verfijn een uitleg totdat het kwartje valt",
"Check an AI explanation is actually correct": "Controleer of een AI-verklaring klopt",
"Understand how the AI works so you trust it right": "Begrijp hoe de AI werkt zodat je er goed op vertrouwt",
"Build a custom study assistant": "Bouw een op maat gemaakte studieassistent",
"Draft a formal letter or form response": "Stel een formele brief of standaardantwoord op",
"Summarise a long document or contract": "Vat een lang document of contract samen",
"Verify a date or deadline that affects you": "Controleer een datum of deadline die jou beïnvloedt",
"Organise and manage personal documents": "Organiseer en beheer persoonlijke documenten",
"Avoid pasting sensitive personal data into public tools": "Vermijd het plakken van gevoelige persoonlijke gegevens in openbare tools",
"Be open you used AI where it matters": "Wees open dat je AI hebt gebruikt waar het ertoe doet",
"Do a quick risk check before an important AI use": "Doe een snelle risicocheck voordat je een belangrijke AI-toepassing uitvoert",
"Help a relative get a useful AI answer": "Help een familielid een nuttig AI-antwoord te krijgen",
"Set up an AI tool safely for a less-confident relative": "Stel een AI-tool veilig in voor een minder zelfverzekerde familielid",
"Model good, open, honest AI use": "Modelleer goed, open, eerlijk AI-gebruik",
"Teach someone a verify-before-share habit": "Leer iemand een gewoonte van verifiëren voordat je deelt.",
"Set a simple AI-use norm for a household or club": "Stel een eenvoudige AI-gebruiksnorm in voor een huishouden of club",
"Tick every point above. 1 still needs confirming.": "Vink elk punt hierboven aan. Er moet er nog 1 bevestigd worden.",
"Install Brigvanti": "Installeer Brigvanti",
"Add it to your home screen. It opens full screen, like an app.": "Voeg Brigvanti toe aan je startscherm. De app opent in full screen, net als een normale app.",
"Not now": "Niet nu",
"Install": "Installeren",
"App": "App",
"Install the app": "Installeer de app",
"Add Brigvanti to your home screen": "Voeg Brigvanti toe aan je startscherm",
"Tap the Share button in your browser. In Safari it can sit under the ⋯ menu.": "Kies in je browser de deelknop. In Safari zit die soms onder het ⋯ menu.",
"Choose Add to Home Screen, then tap Add.": "Kies Voeg toe aan startscherm en kies dan Voeg toe.",
"Open Brigvanti from your home screen and sign in once more.": "Open Brigvanti vanaf je startscherm en log nog één keer in.",
"Open your browser menu.": "Open het menu van je browser.",
"Choose Install app or Add to Home screen.": "Kies App installeren of Toevoegen aan startscherm.",
"Open Brigvanti from your home screen.": "Open Brigvanti vanaf je startscherm.",
"Brigvanti is installed. Open it from your home screen.": "Brigvanti is geïnstalleerd. Open de app vanaf je startscherm.",
"You are offline. Your work is saved on this device. Your coach, sign in and syncing need a connection.": "Je bent offline. Je werk staat veilig op dit apparaat. Voor je coach, inloggen en synchroniseren heb je verbinding nodig."
};
